# Generated by Django 4.2.4 on 2023-08-22 12:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(max_length=100, verbose_name='Numeris')),
                ('vin', models.IntegerField(max_length=100, verbose_name='VIN')),
                ('klientas', models.CharField(max_length=100, verbose_name='Klientas')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Paslaugos pavadinimas')),
                ('kaina', models.FloatField(verbose_name='Paslaugos kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Išleidimo data')),
                ('suma', models.FloatField(verbose_name='Suma')),
                ('status', models.CharField(blank=True, choices=[('l', 'Laukiama apmokėjimo'), ('i', 'Ivykdytas'), ('a', 'Atšauktas'), ('g', 'Grąžintas pavedimas')], default='l', help_text='Užsakymo statusas', max_length=1)),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.automobilis')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.RenameModel(
            old_name='Car',
            new_name='Modelis',
        ),
        migrations.CreateModel(
            name='Uzsakymoeil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(verbose_name='Kiekis')),
                ('kaina', models.FloatField(verbose_name='Kaina')),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.paslauga')),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.uzsakymas')),
            ],
        ),
        migrations.AddField(
            model_name='automobilis',
            name='modelis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.modelis'),
        ),
    ]
