# Generated by Django 4.2.4 on 2023-08-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_automobilis_paslauga_uzsakymas_rename_car_modelis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='vin',
            field=models.IntegerField(verbose_name='VIN'),
        ),
    ]
